[project]
org-name = "kathy"
version = "0.0.1"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "toml4j"
    path = "./libs/mysql-connector-java-8.0.11.jar"
    module = "toml4j"
